### PR TITLE
Add compatibility with Multicompany Module

### PR DESCRIPTION
**Pull request by mapiolca**
Fix an issue that show all documents available in DOLIBARR when Multicompany module activated.

Now, it will show only the documents created by the Portal owner company.

### CODE REVIEW

**Comment by atm-ph** [comment]
I don't understand why are you using `$mysoc->rowid` as entity id  
Can you explain me how you use this module with multicompany?

**Comment by mapiolca** [comment]
For me, each entity is a standalone company. So if one activate the costumer portal, and not the other, so you  shouldn't see invoices, orders and propals from other entities. One portal by entity and not one for all.

**Comment by atm-ph** [comment]
For me the value of `$mysoc->rowid ` is `null` I think it would be `$conf->entity`

If entity is a standalone company for you, I don't understand why you need to use it as filter, to login on the external access the user has an external user access, linked to contact so linked to third party, and we can find the entity like this
After login you sould be on the entity concerned by the user if I merge your pull request we lost the possibility to share documents between entity for the user

**Comment by mapiolca** [comment]
Because All users created by the primary entity and when a user connect to an other entity's portal, he see his documents generated by other entities and not only the owner of portal.

**Comment by atm-john** [comment]
I think there is a mistake of getEntity usage show :

/**
 * 	Get list of entity id to use.
 *
 * 	@param	string	$element		Current element
 *									'societe', 'socpeople', 'actioncomm', 'agenda', 'resource',
 *									'product', 'productprice', 'stock',
 *									'propal', 'supplier_proposal', 'invoice', 'facture_fourn', 'payment_various',
 *									'categorie', 'bank_account', 'bank_account', 'adherent', 'user',
 *									'commande', 'commande_fournisseur', 'expedition', 'intervention', 'survey',
 *									'contract', 'tax', 'expensereport', 'holiday', 'multicurrency', 'project',
 *									'email_template', 'event', 'donation'
 *									'c_paiement', 'c_payment_term', ...
 * 	@param	int		$shared			0=Return id of current entity only,
 * 									1=Return id of current entity + shared entities (default)
 *  @param	object	$currentobject	Current object if needed
 * 	@return	mixed				Entity id(s) to use
 */
function getEntity($element, $shared = 1, $currentobject = null)

**Pull request merged**
